# Generated by Django 6.0.2 on 2026-03-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('descricao', models.CharField(max_length=300)),
                ('codigo_id', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
