# Generated by Django 6.0.2 on 2026-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='img/icon.jpeg', null=True, upload_to='perfil/'),
        ),
    ]
