# Generated by Django 6.0.2 on 2026-03-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='perfil/icon.jpeg', null=True, upload_to='perfil/'),
        ),
    ]
